version: "3.9"

services:
  audio-anonymization-api:
    image: beijuka/audio-anonymization:latest
    container_name: audio-anonymization-api
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - uploads:/app/uploads
      - output:/app/output
      - ./data:/app/data
      - ./params:/app/params
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy_hostinger-network

volumes:
  uploads:
    driver: local
  output:
    driver: local

networks:
  proxy_hostinger-network:
    external: true
